### ISSUE TITLE
Add the `<noscript>` tag to prompt user for enabling JavaScript.

### ISSUE THREAD

**Issue by ImNimboss** [DisnakeDev/website#2]
Add a `<noscript>` tag in index.html for people who don't have JS enabled in their browser, which asks them to enable JS.

**Comment by abhigyantrips** [comment]
Hello, thank you for pointing this out! Though our landing page doesn't depend heavily on JS, it does add to the user experience. 

I've added the `<noscript>` tag [in this commit](https://github.com/DisnakeDev/website/commit/9578596049add62d5e8e02ba437a56e9a7497b2f), and moved to below the GitHub redirect, [here](https://github.com/DisnakeDev/website/commit/fd5d23df83c5c0b08551fafde70c5ad72d6be81e). The position and message of this tag is currently not final, since I'm putting up a hotfix without much discussion with the team. Therefore, things might change in the future.

Once again, thanks for the help!

**Comment by ImNimboss** [comment]
Any chance you could also link https://enable-javascript.com in `<noscript>` to tell the user how to enable javascript? Would be helpful for them :>

**Comment by abhigyantrips** [comment]
Makes sense. Added the same in [this commit](https://github.com/DisnakeDev/website/commit/6805083cff62e957608806ef2a23d637b2d126d4).
